StudentProject/StudentApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("",views.home_view, name = "home"),
    path("signin/", views.signin_view, name = "signin"),
    path('signout/',views.signout_view , name = 'signout'),
    path('staffDetails/',views.staffDetails_view , name = 'staffDetails'),
    path('studentDetails/', views.studentDetails_view , name = 'studentDetails'),
    path('students/<int:id>',views.students_view , name = 'students'),
    path('staff/<int:id>',views.staff_view , name = 'staff'),
    path('fees/',views.fees_view , name = 'fees'),
    path('feedback/',views.feedback_view , name='feedback'),
    path('adminlogin/' , views.adminlogin_view , name = 'adminlogin'),
    path("contactus/", views.contactus_view, name = "contactus"),
    path('aboutus/' , views.aboutus , name = 'aboutus'),
    path('leave/' , views.leave , name = 'leave' ),
    path('deletestudent/<int:id>' , views.deletestudent , name='deletestudent'),



    # student urls
    path('register/',views.register_view , name = 'register'),
    path('registration/', views.registration.as_view() , name = 'registration'),
    path('studentHome/' , views.studentHome_view , name = 'studentHome'),
    path("update/<int:id>", views.update_view, name = "update"),
    path('studentlogin/' , views.studentlogin , name = 'studentlogin'),
    # path('studentsignin/', views.studentsignin , name = 'studentsignin'),
    path('studentprofile/<int:id>', views.studentprofile , name = 'studentprofile'),
    path('studentfeedback/' , views.studentfeedback, name = 'studentfeedback'),
    path('studentleave/' , views.studentleave , name = 'studentleave'),

    #Staff urls
    path('staffregistration/', views.staffregistration.as_view() , name = 'staffregistration'),
    path('staff_signin/',views.staff_signin_view ,name='staff_signin'),
    path('staffhome/' , views.staffhome_view , name = 'staffhome'),
    path("staffupdate/<int:id>", views.staffupdate_view, name = "staffupdate"),
    path('stafflogin/' , views.stafflogin , name = 'stafflogin'),
    path('staffprofile/<int:id>', views.staffprofile , name = 'staffprofile'),
    


]

StudentProject/StudentProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("StudentApp.urls")),
]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

StudentProject/StudentApp/models.py
from django.db import models

# Create your models here.

class StudentModel(models.Model):
    f_name = models.CharField(max_length=100)
    l_name = models.CharField(max_length=100)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=25)
    email = models.EmailField(unique=True)
    contact = models.CharField(max_length=10)
    dob = models.DateField()
    address = models.CharField(max_length=100)
    gender = models.CharField(max_length=100)
    student_image = models.ImageField(upload_to='Student_Image/' , blank=True)
    course = models.CharField(max_length=100)
    department = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    pincode = models.CharField(max_length=6)
    hobbies = models.CharField(max_length=100)
    blood_group = models.CharField(max_length=100)
    known_language = models.CharField(max_length=100)
    education = models.CharField(max_length=100)
    why_you_want = models.CharField(max_length=100)




class StaffModel(models.Model):
    f_name = models.CharField(max_length=100)
    l_name = models.CharField(max_length=100)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=25)
    staff_image = models.ImageField(upload_to='Staff_Image/' , blank=True)
    dob = models.DateField()
    present_address = models.CharField(max_length=100)
    permenant_address = models.CharField(max_length=100)
    contact = models.CharField(max_length=100)
    education = models.CharField(max_length=100)
    project_done = models.CharField(max_length=100)
    work_experience = models.CharField(max_length=100)
    salary_expectations = models.IntegerField()
    material_status = models.CharField(max_length=100)


class FeedbackModel2(models.Model):
    name = models.CharField(max_length=100)
    feedback = models.CharField(max_length=200)


class LeaveModel(models.Model):
    f_name = models.CharField(max_length=100)
    l_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    contact = models.CharField(max_length=10)
    course = models.CharField(max_length=100)
    department = models.CharField(max_length=100)
    reason = models.CharField(max_length=100)


StudentProject/StudentApp/views.py
from django.shortcuts import render, redirect
from . forms import LoginForm , RegisterForm , StaffRegisterForm , StudentLoginForm , StaffloginForm
from django.contrib.auth import authenticate , login , logout
from django.views import View
from . models import StudentModel , StaffModel, FeedbackModel2 , LeaveModel
from django.contrib import messages
# Create your views here.


def home_view(request):
    return render(request , 'StudentApp/home.html')

def adminlogin_view(request):
    forms = LoginForm()
    context = {'forms': forms}
    return render(request , 'StudentApp/adminlogin.html' , context)


def register_view(request):
    forms = RegisterForm()
    context = {'forms': forms}
    return render(request, 'StudentApp/register.html',context)

class staffregistration(View):
    def get(self,request):
        forms = StaffRegisterForm()
        context = {'forms':forms}
        return render (request,"StudentApp/staffRegistration.html",context)

    def post(self,request):
        forms = StaffRegisterForm(request.POST,request.FILES)
        if forms.is_valid():
            forms.save()
            messages.success(request , 'Successfully StaffRegister')
            return redirect('staffregistration')
            
        return redirect('home')


def staff_view(request , id):
    data = StaffModel.objects.get(id=id)
    context = {'data':data}
    return render(request , 'StudentApp/staff.html' , context)


def signin_view(request):
    if request.method == "POST":
        username1 = request.POST['username']
        pass1 = request.POST['password']

        user = authenticate(username = username1 , password = pass1)
        if user is not None:
            login(request,user)
            messages.success(request , 'Successfully admin login')
            return redirect('studentDetails')

    return redirect('home')



def studentDetails_view(request):
    data=StudentModel.objects.all()
    context={'data':data}
    return render(request , 'StudentApp/studentDetails.html',context)

def students_view(request , id):
    data = StudentModel.objects.get(id=id)
    context = {'data':data}
    return render(request , 'StudentApp/students.html',context)



def signout_view(request):
    logout(request)
    messages.info   (request , 'Successfully user logout')
    return redirect('home')


def fees_view(request):
    return render(request, 'StudentApp/fees.html')



def feedback_view(request):
    feedback=FeedbackModel2.objects.all()
    context={'feedback':feedback}
    return render(request , 'StudentApp/feedback.html', context)

def leave(request):
    leave=LeaveModel.objects.all()
    context={'leave':leave}
    return render(request , 'StudentApp/leave.html',context)

def deletestudent(request , id):
    leave = LeaveModel.objects.get(pk = id)
    leave.delete()

    return redirect('leave')


def contactus_view(request):
    return render(request, "StudentApp/contactus.html")

def aboutus(request):
    return render(request , 'StudentApp/aboutus.html')


#Student Section

class registration(View):
    def get(self,request):
        forms = RegisterForm()
        context = {'forms':forms}
        return render (request,"StudentApp/registration.html",context)

    def post(self,request):
        forms = RegisterForm(request.POST,request.FILES)
        if forms.is_valid():
            forms.save()
            messages.success(request , 'Student Successfully Register')
            return redirect('registration')

            
        return redirect('home')

def studentHome_view(request):
    data=StudentModel.objects.all()
    context={'data':data}
    if request.method == "POST":
        email = request.POST['email']
        pass1 = request.POST['password']
        print("email is", email)
        print("password is", pass1)

        model = StudentModel.objects.get(email = email)
        print(model)
        if model.email == email and model.password == pass1:
            messages.success(request , 'Student login ...')
            return render(request , 'StudentApp/StudentHome.html',context)

        else:
            messages.warning(request , 'Please enter valid email id or password ...')
            return redirect('studentlogin')



    # if request.method == "POST":
    #     email = request.POST['email']
    #     pass1 = request.POST['password']

    #     user = StudentModel.objects.get(email = email , password = pass1)
    #     if user is not None:
    #         login(request,user)
    #         messages.success(request , 'Successfully student login')
    #         return redirect('studentDetails')
        




    return render(request , 'StudentApp/StudentHome.html',context)

def studentprofile(request ,id ):
    data = StudentModel.objects.filter(id=id)
    context = {'data':data}
    
    return render(request , 'StudentApp/studentprofile.html', context)


def studentfeedback(request):
    data=StudentModel.objects.all()
    context={'data':data}

    if request.method =='POST':
        name = request.POST["name"]
        feedback = request.POST['feedback']
        
        data = FeedbackModel2(name = name,feedback = feedback)
        messages.success(request , 'Student Feedback Successfully Register')
        data.save()

        return redirect('studentHome')
    return render(request , 'StudentApp/studentfeedback.html',context)

def studentleave(request):
    data=StudentModel.objects.all()
    context={'data':data}

    if request.method =='POST':
        f_name = request.POST["f_name"]
        l_name = request.POST['l_name']
        email = request.POST['email']
        contact = request.POST['contact']
        course = request.POST['course']
        department = request.POST['department']
        reason = request.POST['reason']
        
        data = LeaveModel(f_name = f_name , l_name = l_name , email = email , contact = contact , course = course , department = department, reason = reason)

        data.save()

        return redirect('studentHome')
    return render(request , 'StudentApp/studentleave.html',context )



def update_view(request, id):
    data = StudentModel.objects.get(id = id)
    print("1.data is ", data)
    context = {'data':data}
    

    if request.method == "POST":
        updated_email = request.POST["email"]
        updated_contact = request.POST["contact"]
        updated_address = request.POST["address"]
        updated_course = request.POST["course"]
        updated_department = request.POST["department"]
        updated_city = request.POST["city"]
        updated_education = request.POST["education"]
        

        
        data.email = updated_email
        data.contact = updated_contact
        data.address = updated_address
        data.course = updated_course
        data.department = updated_department
        data.city = updated_city
        data.education = updated_education
        messages.success(request , 'Student Successfully Updated')
        data.save()
        
        return redirect("home")

    return render(request , 'StudentApp/updatestudent.html', context)


def studentlogin(request):
    forms = StudentLoginForm()
    context = {'forms': forms}
    
    return render(request , 'StudentApp/studentlogin.html', context)



# def studentsignin(request):
#     form = StudentLoginForm()
            
#     if request.method == "POST":
#         username = request.POST['username']
#         pass1 = request.POST['password']
#         print("username is", username)
#         print("password is", pass1)

        # user = authenticate(username = username , password = pass1)
        # print(user)
        # if user is not None:
        #     login(request,user)
        #     # messages.success(request , 'Successfully user login')
        #     return redirect('studentDetails')

    # context = {'form':form}
    # return redirect('home')



#Staff section

def staffDetails_view(request):
    data=StaffModel.objects.all()
    context={'data':data}
    return render(request , 'StudentApp/staffDetails.html' , context)


def staff_signin_view(request):

    # forms = StaffRegisterForm()
    # if request.method == "POST":
    #     username1 = request.POST['username']
    #     pass1 = request.POST['password']

    #     user = authenticate(username = username1 , password = pass1)
    #     if user is not None:
    #         login(request,user)
    #         # messages.success(request , 'Successfully staff login')
    #         return redirect('staffDetails')

    #     return redirect('home')
    # context = {"forms":forms}
    return render(request , 'StudentApp/registration.html')


def staffhome_view(request):
    data=StaffModel.objects.all()
    context={'data':data}

    if request.method == "POST":
        username = request.POST['username']
        pass1 = request.POST['password']
        print("username is", username)
        print("password is", pass1)

        staff = StaffModel.objects.get(username = username)
        print(staff)
        if staff.username == username and staff.password == pass1:
            messages.success(request , 'Staff login ...')
            return render(request , 'StudentApp/staffhome.html',context)

        else:
            messages.warning(request , 'Please enter valid username id or password ...')
            return redirect('stafflogin')
    

def staffupdate_view(request ,id):
    
    data = StaffModel.objects.get(id = id)
    print("1.data is ", data)
    context = {'data':data}
    

    if request.method == "POST":
    
        updated_contact = request.POST["contact"]
        updated_present_address = request.POST["present_address"]

StudentProject/templates/StudentApp/StudentHome.html
{% extends 'StudentApp/StudentBase.html' %}
{% load static %}





<!-- CSS block  -->

{% block css %}
{% endblock css %}

<!-- js block  -->

{% block js %}

{% endblock js %}

<!-- title block  -->
{% block title %}
<title>Student Home Page</title>
{% endblock title %}

<!-- body block  -->
{% block body %}


<div class="container mt-5 py-4" style="background-color: bisque;">

    
    
    <div class="container p-3  text-center rounded" style="background-color:beige; border: 2px dashed black;">
        <h1 class="display-6">Student Home Page</h1>
    </div>
    
    <p class="container border border-dark mt-5" style="background-color: aquamarine;"><b>Note: </b> This is page of student information. All the students are given information on this. If you want to see your information, you can see your information by clicking on the email on your information.</p>

    {% for d in data %}
    <div class="container p-3 my-3 shadow rounded mt-5" style="background-color:white;">
        
        <h1>{{d.f_name}} {{d.l_name}}</h1>
        <a href="{% url 'studentprofile' d.id %}">{{d.email}}</a>
        

        
        
    </div>
    
    {% endfor %}

    

</div>

{% endblock body %}

StudentProject/templates/StudentApp/adminlogin.html
{% extends 'StudentApp/base.html' %}
{% load static %}





<!-- CSS block  -->

{% block css %}
{% endblock css %}

<!-- js block  -->

{% block js %}

<script>
    $(document).ready(function(){
        $('#id_dob').datepicker({
            changeMonth:true,
            changeYear:true,
            yearRange:'1970:2049'
        });
    });
</script>
{% endblock js %}

<!-- title block  -->
{% block title %}
<title>Admin login Page</title>
{% endblock title %}

<!-- body block  -->
{% block body %}

<!-- main container  -->
<div class="container mt-5 " style="border: 1px solid black;">
    
    <div class="row px-3 my-5">
        <!-- left section  -->
        <div class="col-7">
            <!-- image section  -->
            <div>
                <h1 class="display-4">Student Management system</h1>
            <img class="mt-3" style="border: 3px dashed black;" src="{% static 'StudentApp/images/sign.jpg' %}" alt="no image" height="350px" width="700px">
            </div>

        
        </div>

        <!-- right section  -->

        <div class="col-5 mt-5">
            <div class="shadow rounded p-5" style="background-color: bisque;">
                <div class="my-5">
                    <form action="{% url 'signin' %}" method="post">
                        {% csrf_token %}
                        <!-- widgt comes from backend  -->
                        {% for fm in forms %}

                        <div class="mb-3">
                            {{fm.label_tag}}
                            {{fm}}
                            <span style="color:red;">{{fm.errors}}</span>
                        </div>

                        {% endfor %}


                        <div class="mb-3 text-center">
                            <input type="submit" value="login" class="btn btn-outline-primary btn-lg">
                        </div>
                    </form>
                </div>

                
            </div>
        </div>
        
    </div>


    


   
</div>

<div class="container border-top border-dark mt-5">

    <div class="container mt-5" >
    
    <div class="row" >
    
    <div class="col-4 border-end">
        <h3 class="mb-4">About us</h3>
        <p>A Student Management System is also known as a Student Information System (SIS). These systems work to coordinate scheduling and communications between faculty regarding students. This system exists to simplify information tracking for both parents and administrative staff.</p>
    
        <a href="{% url 'aboutus' %}" style="text-decoration: none;">Learn More <i class="bi bi-arrow-right"></i></a>
    </div>
    
    <div class="col-4 text-center border-end" >
    
        <h3 class="mb-4">Menu</h3>
        <p><a href="{% url 'home' %}" style="text-decoration: none; color: black;">Home</a></p>
        <p><a href="{% url 'registration' %}" style="text-decoration: none; color: black;">Student Registration</a></p>
        <p><a href="{% url 'staffregistration' %}" style="text-decoration: none; color: black;">Staff Registration</a></p>
        <p><a href="{% url 'adminlogin' %}" style="text-decoration: none; color: black;">Admin Login</a> </p>
        <p><a href="{% url 'feedback' %}" style="text-decoration: none; color: black;">Feedback</a> </p>
        <p><a href="{% url 'contactus' %}" style="text-decoration: none; color: black;">Contact us</a> </p>
        <p><a href="{% url 'aboutus' %}" style="text-decoration: none; color: black;">About Us</a> </p>
    
    
    </div>
    
    <div class="col-4 text-center" 
    
        <h3 class="mb-4">Contact Us</h3>
        Phone Number: 
        <h6>9158176742</h6>
        Email ID:
        <h6>jagrutibhande242001@gmail.com</h6>
    
    
    </div>
    
    
    
    </div>
    </div>
    </div>
{% endblock body %}

StudentProject/templates/StudentApp/adminviewfeedback.html
{% extends 'StudentApp/base.html' %}
{% load static %}





<!-- CSS block  -->

{% block css %}
{% endblock css %}

<!-- js block  -->

{% block js %}
{% endblock js %}

<!-- title block  -->
{% block title %}
<title>Admin View Feedback Page</title>
{% endblock title %}

<!-- body block  -->
{% block body %}

<div class="container mt-5 py-4" style="background-color: bisque;">
    <div class="container p-3  text-center rounded" style="background-color:beige; border: 2px dashed black;">
        <h1 class="display-6">Feedback Page</h1>
    </div>

    <div class="container text-center shadow mt-4">
        {% for fb in feedback %}
        <div class="mb-3">
            <div class="row">
                <div class="col-3 s">
                     {{fb.name}}

                </div>
                <div class="col-9 lead ">
                    {{fb.feedback}}
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
    

    

    
</div>

{% endblock body %}

StudentProject/templates/StudentApp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <!-- Css Link  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <!-- JS link  -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


    <!-- CDN link  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

    <!-- blocks  -->

    {% block css %}
    {% endblock css %}

    <!-- js block  -->

    {% block js %}
    {% endblock js %}

    <!-- title block  -->
    {% block title %}
    {% endblock title %}
</head>
<body>
    {% include 'StudentApp/navbar.html' %}

    {% if messages %}

    {% for message in messages %}

    <p  {% if message.tags %} class="alert alert-{{message.tags}} " {% endif %}>{{message}}</p>

    {% endfor %}

    {% endif %}

    <!-- body block  -->
    {% block body %}

    
    {% endblock body %}
    
</body>
</html>

StudentProject/templates/StudentApp/contactus.html
{% extends 'StudentApp/base.html' %}
{% load static %}





<!-- CSS block  -->

{% block css %}
{% endblock css %}

<!-- js block  -->

{% block js %}

{% endblock js %}

<!-- title block  -->
{% block title %}
<title>contact us Page</title>
{% endblock title %}

<!-- body block  -->
{% block body %}

<div class="container mt-5 py-4" style="background-color: bisque;">
    <div class="container p-3  text-center rounded" style="background-color:beige; border: 2px dashed black;">
        <h1 class="display-6">Contact us Page</h1>
    </div>

</div>

<div class="container mt-5 shadow p-5 w-50" style="border: 1px solid black; background-color: darkgray;">
    <h2>Email ID</h2>
    <p>jagrutibhande242001@gmail.com</p>
    <h2>Contact Number:</h2>
    <p>9158176742</p>
</div>


<div class="container border-top border-dark mt-3">

    <div class="container mt-5" >
    
    <div class="row" >
    
    <div class="col-4 border-end">
        <h3 class="mb-4">About us</h3>
        <p>A Student Management System is also known as a Student Information System (SIS). These systems work to coordinate scheduling and communications between faculty regarding students. This system exists to simplify information tracking for both parents and administrative staff.</p>
    
        <a href="{% url 'aboutus' %}" style="text-decoration: none;">Learn More <i class="bi bi-arrow-right"></i></a>
    </div>
    
    <div class="col-4 text-center border-end" >
    
        <h3 class="mb-4">Menu</h3>
        <p><a href="{% url 'home' %}" style="text-decoration: none; color: black;">Home</a></p>
        <p><a href="{% url 'registration' %}" style="text-decoration: none; color: black;">Student Registration</a></p>
        <p><a href="{% url 'staffregistration' %}" style="text-decoration: none; color: black;">Staff Registration</a></p>
        <p><a href="{% url 'adminlogin' %}" style="text-decoration: none; color: black;">Admin Login</a> </p>
        <p><a href="{% url 'feedback' %}" style="text-decoration: none; color: black;">Feedback</a> </p>
        <p><a href="{% url 'contactus' %}" style="text-decoration: none; color: black;">Contact us</a> </p>
        <p><a href="{% url 'aboutus' %}" style="text-decoration: none; color: black;">About Us</a> </p>
    
    
    </div>
    
    <div class="col-4 text-center" 
    
        <h3 class="mb-4">Contact Us</h3>
        Phone Number: 
        <h6>9158176742</h6>
        Email ID:
        <h6>jagrutibhande242001@gmail.com</h6>
    
    
    </div>
    
    
    
    </div>
    </div>
    </div>


{% endblock body %}


StudentProject/templates/StudentApp/feedback.html
{% extends 'StudentApp/base.html' %}
{% load static %}





<!-- CSS block  -->

{% block css %}
{% endblock css %}

<!-- js block  -->

{% block js %}
{% endblock js %}

<!-- title block  -->
{% block title %}
<title>Feedback Page</title>
{% endblock title %}

<!-- body block  -->
{% block body %}

<div class="container mt-5 py-4" style="background-color: bisque;">
    <div class="container p-3  text-center rounded" style="background-color:beige; border: 2px dashed black;">
        <h1 class="display-6">Feedback Page</h1>
    </div>

    <div class="container text-center  shadow mt-4" style="background-color:darkgrey; ">
    <div class="mb-3">
        <div class="row">
            <div class="col-4 p-2 border border-dark">
                 <h3>Name</h3>

            </div>
            <div class="col-8 p-2 border-dark border">
               <h3> Feedback</h3>
            </div>
        </div>
    </div>
</div>


    <div class="container text-center shadow mt-4" style="background-color:cornsilk;">
        {% for fb in feedback %}
        <div class="mb-3">
            <div class="row border-end border-bottom border-dark">
                <div class="col-4 border-end border-dark ">
                     <h3>{{fb.name}} </h3>

                </div>
                <div class="col-8  ">
                    {{fb.feedback}}
                </div>
            </div>
        </div>

        {% endfor %}
    </div>

    <div class="container px-2 text-center">
        <img src="{% static 'StudentApp/images/feedback.png/' %}" alt="No image" height="400px" width="1000px" style="border: 2px solid black;">
    </div>

</div>

<div class="container border-top border-dark mt-5">

    <div class="container mt-5" >
    
    <div class="row" >
    
    <div class="col-4 border-end">
        <h3 class="mb-4">About us</h3>
        <p>A Student Management System is also known as a Student Information System (SIS). These systems work to coordinate scheduling and communications between faculty regarding students. This system exists to simplify information tracking for both parents and administrative staff.</p>
    
        <a href="{% url 'aboutus' %}" style="text-decoration: none;">Learn More <i class="bi bi-arrow-right"></i></a>
    </div>
    
    <div class="col-4 text-center border-end" >
    
        <h3 class="mb-4">Menu</h3>
        <p><a href="{% url 'home' %}" style="text-decoration: none; color: black;">Home</a></p>
        <p><a href="{% url 'registration' %}" style="text-decoration: none; color: black;">Student Registration</a></p>
        <p><a href="{% url 'staffregistration' %}" style="text-decoration: none; color: black;">Staff Registration</a></p>
        <p><a href="{% url 'adminlogin' %}" style="text-decoration: none; color: black;">Admin Login</a> </p>
        <p><a href="{% url 'feedback' %}" style="text-decoration: none; color: black;">Feedback</a> </p>
        <p><a href="{% url 'contactus' %}" style="text-decoration: none; color: black;">Contact us</a> </p>
        <p><a href="{% url 'aboutus' %}" style="text-decoration: none; color: black;">About Us</a> </p>
    
    
    </div>
    
    <div class="col-4 text-center" 
    
        <h3 class="mb-4">Contact Us</h3>
        Phone Number: 
        <h6>9158176742</h6>
        Email ID:
        <h6>jagrutibhande242001@gmail.com</h6>
    
    
    </div>
    
    
    
    </div>
    </div>
    </div>
{% endblock body %}

StudentProject/templates/StudentApp/stafflogin.html
{% extends 'StudentApp/staffBase.html' %}
{% load static %}





<!-- CSS block  -->

{% block css %}
{% endblock css %}

<!-- js block  -->

{% block js %}
{% endblock js %}

<!-- title block  -->
{% block title %}
<title>staff login Page</title>
{% endblock title %}

<!-- body block  -->
{% block body %}

<div class=" mt-5 text-center">
    <div class="container w-50 p-3 " style="background-color:darkgray; border: 1px solid black;">
        <h1>Staff Login</h1>
    </div>
    <div class="container w-50 shadow rounded mt-5 p-5 " style="border: 2px solid black;">
        <div class="container w-50 text-center" >
            <form action="{% url 'staffhome' %}" method="post">
                {% csrf_token %}
                <!-- widgt comes from backend  -->
                <div class="my-3">
                    <label for="username">Enter Staff username</label>
                    <input type="username" name="username" id="username" class="form-control" value="{{form.username}}">
                </div>

                <div class="my-3">
                    <label for="password">Enter Staff Password</label>
                    
                    <input type="password" name="password" id="password" class="form-control" value="{{form.password}}">
                </div>


                <div class="mb-3 text-center">
                    <input type="submit" value="login" class="btn btn-outline-primary btn-lg">
                </div>
            </form>
        </div>
        
        </div>
</div>


{% endblock body %}